/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/'use strict';

var _wp = wp,
    registerBlockType = _wp.blocks.registerBlockType,
    InnerBlocks = _wp.blockEditor.InnerBlocks;
var _Drupal = Drupal,
    __ = _Drupal.t;


var style = {
  minHeight: '40px',
  margin: '0 -40px',
  padding: '0 40px'
};

var settings = {
  title: __('Root'),
  icon: 'media-document',
  attributes: {},
  supports: {
    inserter: false,
    align: true,
    html: false
  },

  edit: function edit() {
    return React.createElement(
      'main',
      { style: style },
      React.createElement(InnerBlocks, { templateLock: false, template: [['core/paragraph', {}]] })
    );
  },
  save: function save(_ref) {
    var className = _ref.className;

    return React.createElement(
      'main',
      { className: className },
      React.createElement(InnerBlocks.Content, null)
    );
  }
};

registerBlockType('custom/root', settings);