name: Build
on:
  - push

jobs:

  pnpm_7_29_1:
    name: pnpm@7.29.1
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm@7.29.1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm build

  pnpm_7_29_2:
    name: pnpm@7.29.2
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm@7.29.2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm build
